# flake8: noqa: E401E
from music_scraper.album_finders.album_finder_base import AlbumFinderBase
from music_scraper.album_finders.album_finder_aoty import AlbumFinderAOTY
from music_scraper.album_finders.album_finder_bandcamp import AlbumFinderBandcamp
